#!/bin/bash

BG="#30303a"
FG1="#b4b4b4"
FG2="#dcdcdc"
YPOS="16"
red="#da637e"
redb="#f0a3a3"
blue="#7c96c9"
blueb="#a8c9eb"
green="#7cc988"
greenb="#b0deb7"

background="#30303a"
foreground="#eeeeee"
highlight="#b4b4b4"

FONT="-artwiz-lemon-medium-r-normal-*-10-110-75-75-m-50-iso8859-*"
white0="#626e74"

bar_bg="#404040"
notify="#F39D21"
warning="#D23D3D"
