#!/bin/bash

source $(dirname $0)/d-conf

FREE=$(df -h | grep "/dev/sd" | sed -n "1p" | awk -F " " '{print $3}' | sed s/G//g | awk '{printf "%.0f\n", $1}')
PERC=$(df -h | grep "/dev/sd" | sed -n "1p" | awk -F " " '{print $5}' | sed s/G//g | awk '{printf "%.0f\n", $1}')

if [[ "$PERC" -gt "75" ]]; then
	PERCBAR=`echo -e "$PERC"\
	| gdbar -bg $bar_bg -fg $warning -h 1 -w 130`
else
	PERCBAR=`echo -e "$PERC"\
	| gdbar -bg $bar_bg -fg $foreground -h 1 -w 130`
fi

echo "^fg($FG2)⮤ ^fg()  $PERCBAR ^fg($highlight)$PERC%"
