#!/bin/bash
source $(dirname $0)/d-conf

FREE=`free -m | sed -n "2p" | awk -F " " '{print $3}'`
MAX=`free -m | sed -n "2p" | awk -F " " '{print $2}'`
PERC=`echo $FREE*100/$MAX | bc`

if [[ $PERC -gt 75 ]]; then
	PERCBAR=`echo -e "$PERC"\
	| gdbar -bg $bar_bg -fg $warning -h 1 -w 115`
else
	PERCBAR=`echo -e "$PERC"\
	| gdbar -bg $bar_bg -fg $foreground -h 1 -w 115`
fi

echo "^fg($FG2) ⮥ RAM^fg()  $PERCBAR ^fg($highlight)$PERC%"
