#!/bin/bash

source $(dirname $0)/d-conf

#YPOS="14"
XPOS=$(( $(xdotool getmouselocation | awk -F " " '{print $1}' | cut -d ":" -f 2) - 55 ))
#TIMING="5"
 
HEIGHT="12"
WIDTH="108"
LINES="10"
ALIGN="left"

ti=$(date | awk -F " " '{print $4}')
day=$(date +%D)
calendar=$(cal -1)

(echo "^fg($red)Time"; echo "^fg($FG2)Time: ^fg($FG1)$ti"; echo "^fg($FG2)Date: ^fg($FG1)$day"; echo ; echo "^fg($FG2)$calendar";sleep $TIMING) | dzen2 -bg $BG -fn $FONT -x $XPOS -y $YPOS -w $WIDTH -h $HEIGHT -l $LINES -e 'onstart=uncollapse;button1=exit;button2=exit;button3=exit;button4=exit;button5=exit'
