#!/bin/bash

source $(dirname $0)/d-conf

if [[ $rescheck == "1600x900" ]]; then
  XPOS=1451
else
  XPOS=1770
fi

HEIGHT="12"
WIDTH="144"
LINES="8"
ALIGN="left"

avol=$(amixer | grep "Master" -A 5 | grep -o "\[.*%" | sed "s/\[//")
alsavol="^fg($FG2)Alsa Volume: ^fg($FG1)$avol"
cover="cd /home/phallus/bin;./cover_fetcher"

buttons=" ^ca(1, mpc prev)⮳  ^ca()  ^ca(1, mpc pause)⮔  ^ca() ^ca(1, $cover)↓  ^ca() ^ca(1, mpc play)⮓ ^ca()  ^ca(1, mpc next)⮲  ^ca() "

if [ "`mpc 2>&1 | wc -l`" -gt "1" ]; then
	so=`mpc current -f %title%`
  np="^fg($FG2)$so"
	arta=`mpc current -f %artist%`
	alba=`mpc current -f %album%`
	artb=`mpc current -f %artist% | sed -e 's/\//-/g'| sed -e 's/|/-/g' | sed -e 's/\://g'`
  albb=`mpc current -f %album% | sed -e 's/\//-/g'| sed -e 's/|/-/g' | sed -e 's/\[//g' | sed -e 's/\]//g'`

  #this is entirely unnecessary, but i like it
  lena=`echo ${#arta}`
  if [ "$lena" -gt 19 ]; then
    art=`echo ${arta:0:18}…`
  else
    art=$arta
  fi
  
  lenb=`echo ${#alba}`
  if [ "$lenb" -gt 20 ]; then
    alb=`echo ${alba:0:19}…`
  else
    alb=$alba
  fi

  lenc=`echo ${#so}`
  if [ "$lenc" -gt 27 ]; then
    trim=`echo $so | cut -c1-26`
    np1=`echo $trim…`
  else
    np1=$np
  fi

	ti=$(mpc | sed -n "2p" | awk -F " " '{print $3}')
	artist="^fg($FG2)Artist: ^fg($FG1)$art"
	album="^fg($FG2)Album: ^fg($FG1)$alb"
	time="^fg($FG2)Time: ^fg($FG1)$ti"
	
	perc=`mpc | awk 'NR == 2 {gsub(/[()%]/,""); print $4}'`
	percwidth=$(( $WIDTH - 10 ))
	percbar=`echo -e "$perc" | gdbar -bg $bar_bg -fg $foreground -h 1 -w $percwidth`
	albumart="/home/phallus/mu/thumbs/$(ls ~/mu/thumbs | grep "$artb - $albb.png")"
	
	nowplaying="$np1"
	playing=$(mpc current)
	playlistcurrent=$(mpc playlist | grep -n "$playing" | cut -d ":" -f 1)
	tnum=$(mpc -f %track% | sed -n "1p")
	track="^fg($FG2)Track Number: ^fg($FG1)$tnum"	
	mvol=$(mpc volume | awk -F " " '{print $2}')
	
  exec -a albumartpopup feh -N -B black -g +$(($XPOS-108))+$(($YPOS)) "$albumart" --title "aart" &
  
  #do to -- close only feh process created by this script instead of all feh processes
	(echo "$nowplaying"; echo " $artist"; echo " $album"; echo " $time"; echo " $track"; echo " "; echo " $percbar";echo "^fg($cyan)    $buttons"; echo " "; sleep $TIMING) | dzen2 -bg $BG -fn $FONT -x $XPOS -y $YPOS -w $WIDTH -h $HEIGHT -l $LINES -e 'onstart=uncollapse;button1=exit;button2=exit;button3=exit;button4=exit;button5=exit;onexit=exec:pkill -f albumartpopup'
else
	(echo "^fg($FG2)MPD is not playing."; sleep 1) | dzen2 -bg $BG -fn $FONT -x $XPOS -y $YPOS -w 95 -h $HEIGHT -l 0 -ta "center" -sa $ALIGN -e 'onstart=uncollapse;button1=exit;button2=exit;button3=exit;button4=exit;button5=exit'
fi
